spring.application.name=demo


management.endpoints.web.exposure.include=mappings
spring.mvc.log-resolved-exception=true
logging.level.org.springframework.web=DEBUG
spring.mvc.log-request-details=true
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
